### ISSUE TITLE
azure-sp-tool create-sp fails

### ISSUE THREAD

**Issue by hpejcinovic-pivotal** [danhigham/azure-sp-tool#3]
I'm having the same issue when creating azure-sp-tool create-sp
fails with 
Creating application...ERROR: Error: We don't have a valid access token. Please run "azure login" again.
/usr/local/lib/node_modules/azure-sp-tool/index-create-sp.js:143
    clientID: clientId.appId,
                      ^

TypeError: Cannot read property 'appId' of null
    at /usr/local/lib/node_modules/azure-sp-tool/index-create-sp.js:143:23
    at /usr/local/lib/node_modules/azure-sp-tool/node_modules/async/dist/async.js:484:16
    at /usr/local/lib/node_modules/azure-sp-tool/node_modules/async/dist/async.js:5200:33
    at apply (/usr/local/lib/node_modules/azure-sp-tool/node_modules/async/dist/async.js:41:25)
    at /usr/local/lib/node_modules/azure-sp-tool/node_modules/async/dist/async.js:76:12
    at /usr/local/lib/node_modules/azure-sp-tool/node_modules/async/dist/async.js:988:16
    at /usr/local/lib/node_modules/azure-sp-tool/index-create-sp.js:114:9
    at /usr/local/lib/node_modules/azure-sp-tool/node_modules/azure-graph/lib/operations/applicationOperations.js:151:14
    at retryCallback (/usr/local/lib/node_modules/azure-sp-tool/node_modules/ms-rest/lib/filters/exponentialRetryPolicyFilter.js:140:9)
    at handleRedirect (/usr/local/lib/node_modules/azure-sp-tool/node_modules/ms-rest/lib/filters/redirectFilter.js:36:9)

**Comment by cnow7** [comment]
@hpejcinovic-pivotal I was able to get the azure-credentials.json by following this tutorial: http://blog.erds.xyz/technology/install-cloud-foundry-on-azure/.

Basically, I had to install and use Docker to get this done. I have no idea why doing it with Docker ends up doing the trick.
